project:
  type: website
  output-dir: docs

website:
  title: "Momentum Data Protocol"
  navbar:
    background: primary
    logo: logo.png
    logo-alt: 'Momentum logo'
    title: false
    left:
      - href: index.qmd
        text: Home
        - text: "About Momentum"
          href: about.qmd
        - text: "Data flow guide"
          href: guide.qmd
        - text: "Template Designer"
          href: designer.qmd
        - text: "Naming convention"
          href: naming.qmd
    search: true
  page-navigation: true
  back-to-top-navigation: true

format:
  html:
    embed-resources: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-title: Content
    toc-location: left
    toc-depth: 4



