---
title: "Momentum Data protocol"
---

This is a draft website describing the workflow of Momentum data. 
It is written mainly for data generators of Momentum.

The website provides practical steps to help Momentum researchers align with the FAIR data management practices established in the project. Links are provided to chosen resources (for data transfer and publishing).


#### Further references
The data management practices described here are specific for Momentum. However, in a big part these recommendations are based on and complemented by other more generic or elaborate reasources on e.g. data storage, archiving etc.
Please make sure to check those out as well.

> [The Turing way](https://book.the-turing-way.org/) - open source community-driven guide to reproducible, ethical, inclusive and collaborative data science. The Turing Way book is collaboratively developed by its diverse community of researchers, learners, educators, and other stakeholders.
DOI: 10.5281/zenodo.3233853

> [VU Research Support Handbook](https://ubvu.github.io/open-handbook/) - community led handbook for all things related to research at VU. 
Disclaimer: "All information in the handbook is specific to VU's local context."

> [Data Privacy Handbook, UU](https://utrechtuniversity.github.io/dataprivacyhandbook/) - a guide to handling personal data in scientific research, in line with European data protection and privacy regulations. 
DOI: 10.5281/zenodo.8005847

::: {.callout-tip icon="false" appearence="simple"}
Additionally, you can always consult the [resources](https://www.uu.nl/en/research/research-data-management) from the Central Research Manangement Support of Utrecht University. 
:::

