---
title: "Naming Convention"
---


### Naming convention for Momentum data

Name files as follows:
[Partner]\_[Template]\_[Initials/ID]\_[Nr].[Extension]

---
tbl-cap-location: bottom
---

+-------------+-----------------------------------------------------------------------+
| Section     | Explanation                                                           |
+=============+===========+===========================================================+
| Partner     |  - UU = Utrecht University                                            |
|             |  - UMCU = UMC Utrecht                                                 |
|             |  - RUG = University of Groningen                                      |
|             |  - OU = Open University                                               |
|             |  - UM = Maastricht University                                         |
|             |  - UTWENTE = Technical University of Twente                           |
|             |  - UV = Vrije Universiteit Amsterdam                                  |
|             |  - WUR = Wageningen University & Research                             |
|             |  - DELT = Stichting Deltares                                          |
|             |  - KWR = KWR                                                          |
|             |  - RIVM = National Institute for Public Health and the Environment    |
|             |  - TNO = TNO                                                          |
|             |  - UHASSELT = Hasselt University                                      |
+-------------+-----------------------------------------------------------------------+
| Templates   |  - elisa = ELISA                                                      |
|             |  - qpcr = qPCR                                                        |
|             |  - ldh = LDH leakage                                                  |
|             |  - alamb = Alamarblue                                                 |
|             |  - mea = Microelectrode array                                         |
|             |  - neutr-surv = Neutrophil survival                                   |
|             |  - py-gc-ms = Pyrolysis GC/MS                                         |
|             |  - doseresp = generic ‘doseresponse_table’ template                   |
|             |  - sem-md = SEM metadata                                              |
|             |  - hts-md = HTS metadata                                              |
|             |  - ...                                                                |
|             |                                                                       |
|             | ‘md’ stands for metadata                                              |
|             |                                                                       |
|             | follow same naming for non-tabular data that is described by metadata |
|             | just name 'template' without '-md'                                    |
|             |                                                                       |
|             | **further templates should be named with lowercase letters and hyphen |
|             | aim to be concise but be clear on type of template**                  |
+-------------+-----------------------------------------------------------------------+
| Initials/ID | Initials/numeric ID code of data generator                            |
+-------------+-----------------------------------------------------------------------+
| Nr          | Deliberate numbering to differentiate between templates of given      |
|             | data generator                                                        |
+-------------+-----------------------------------------------------------------------+
| Extension   | Mainly foreseen to be .xls (except for non-tabular data)              |
+-------------+-----------------------------------------------------------------------+

: Naming of data files {.hover}


::: {.callout-note icon="false" appearence='simple'}
This way of naming makes it easy to trace back potential incorrectness of data, in case amendments to the eNanomapper database are necessary.
:::
